/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

#include <stdio.h>

int main() {
    int i, sum;
    float x, prod;
    double y, result;

line_100:
    /* Test all numeric types */
line_110:
    i = 42;
line_120:
    x = 3.14159;
line_130:
    y = 2.718281828459045;
line_140:
    printf("%d\n", i);
line_150:
    printf("%g\n", x);
line_160:
    printf("%lg\n", y);
line_170:
    /* Test expressions */
line_180:
    sum = (i + 10);
line_190:
    prod = (x + x);
line_200:
    result = (y + x);
line_210:
    printf("%d\n", sum);
line_220:
    printf("%g\n", prod);
line_230:
    printf("%lg\n", result);
line_240:
    return 0;

    return 0;
}
