/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

#include <stdio.h>

int main() {
    double x, y, z;

line_100:
    /* Test DOUBLE precision floating point */
line_110:
    x = 3.141592653589793;
line_120:
    y = 2.718281828459045;
line_130:
    printf("%lg\n", x);
line_140:
    printf("%lg\n", y);
line_150:
    z = (x + y);
line_160:
    printf("%lg\n", z);
line_170:
    return 0;

    return 0;
}
