/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

#include <stdio.h>

int main() {
    int i;

    /* GOSUB return stack */
    int gosub_stack[100];  /* Return line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_100:
    /* Test GOSUB/RETURN */
line_110:
    i = 1;
line_120:
    gosub_stack[gosub_sp++] = 0;  /* Push return address */
    goto line_200;  /* Jump to subroutine */
gosub_return_0:  /* Return point */
line_130:
    i = 2;
line_140:
    gosub_stack[gosub_sp++] = 1;  /* Push return address */
    goto line_200;  /* Jump to subroutine */
gosub_return_1:  /* Return point */
line_150:
    printf("%d\n", 99);
line_160:
    return 0;
line_200:
    /* Subroutine */
line_210:
    printf("%d\n", i);
line_220:
    if (gosub_sp > 0) {
        switch (gosub_stack[--gosub_sp]) {
            case 0: goto gosub_return_0;
            case 1: goto gosub_return_1;
            default: break;  /* Error: invalid return address */
        }
    }

    return 0;
}
