/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

#include <stdio.h>

int main() {
    /* GOSUB return stack */
    int gosub_stack[100];  /* Return line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_100:
    /* Test nested GOSUB and loops */
line_110:
    printf("%d\n", 1);
line_120:
    gosub_stack[gosub_sp++] = 0;  /* Push return address */
    goto line_300;  /* Jump to subroutine */
gosub_return_0:  /* Return point */
line_130:
    printf("%d\n", 4);
line_140:
    return 0;
line_200:
    /* Inner subroutine */
line_210:
    printf("%d\n", 3);
line_220:
    if (gosub_sp > 0) {
        switch (gosub_stack[--gosub_sp]) {
            case 0: goto gosub_return_0;
            default: break;  /* Error: invalid return address */
        }
    }
line_300:
    /* Outer subroutine */
line_310:
    printf("%d\n", 2);
line_320:
    gosub_stack[gosub_sp++] = 1;  /* Push return address */
    goto line_200;  /* Jump to subroutine */
gosub_return_1:  /* Return point */
line_330:
    if (gosub_sp > 0) {
        switch (gosub_stack[--gosub_sp]) {
            case 0: goto gosub_return_0;
            case 1: goto gosub_return_1;
            default: break;  /* Error: invalid return address */
        }
    }

    return 0;
}
