/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

#include <stdio.h>

int main() {
    int i, j, k;

    /* GOSUB return stack */
    int gosub_stack[100];  /* Return line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_100:
    /* Comprehensive scoping test */
line_110:
    /* Test FOR loop with GOSUB */
line_120:
    for (i = 1; i <= 3; i += 1) {
line_130:
        gosub_stack[gosub_sp++] = 0;  /* Push return address */
        goto line_300;  /* Jump to subroutine */
gosub_return_0:  /* Return point */
line_140:
    }
line_150:
    /* Test WHILE loop with GOTO */
line_160:
    j = 1;
line_170:
    while ((j <= 2)) {
line_180:
        printf("%d\n", j);
line_190:
        j = (j + 1);
line_200:
    }
line_210:
    return 0;
line_300:
    /* Subroutine with nested WHILE */
line_310:
    k = i;
line_320:
    while ((k > 0)) {
line_330:
        printf("%d\n", k);
line_340:
        k = (k - 1);
line_350:
    }
line_360:
    if (gosub_sp > 0) {
        switch (gosub_stack[--gosub_sp]) {
            case 0: goto gosub_return_0;
            default: break;  /* Error: invalid return address */
        }
    }

    return 0;
}
