/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

#include <stdio.h>

int main() {
    float i;

line_100:
    for (i = 0.0; i <= 10.0; i += 1) {
line_110:
        printf("%d\n", i);
line_120:
    }
line_130:
    return 0;

    return 0;
}
