/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

#include <stdio.h>

int main() {
    float x, i;

line_100:
    /* Unsupported: RemarkStatementNode */
line_110:
    x = 3.14159;
line_120:
    for (i = 0.5; i <= 5.5; i += 0.5) {
line_130:
        printf("%g\n", i);
line_140:
    }
line_150:
    printf("%g\n", x);
line_160:
    return 0;

    return 0;
}
