/* Generated by MBASIC-2025 compiler */
/* Target: CP/M via z88dk */

#include <stdio.h>

int main() {
    int i;

    /* GOSUB return stack */
    int gosub_stack[100];  /* Return line numbers */
    int gosub_sp = 0;      /* Stack pointer */

line_100:
    /* Test WHILE/WEND loop */
line_110:
    i = 1;
line_120:
    while ((i <= 5)) {
line_130:
        printf("%d\n", i);
line_140:
        i = (i + 1);
line_150:
    }
line_160:
    printf("%g\n", 0  /* unsupported expression */);
line_170:
    return 0;

    return 0;
}
